### ISSUE TITLE
Crash of the physics engine during the MCreator slabs

### ISSUE THREAD

**Issue by raphaelcolau** [DynamXInc/DynamX#38]
**Describe the bug**
When a player passes over an mcreator tile with a DynamX vehicle, the physics engine crashes and it is necessary to remove the player data.

**Error**
```

[08:50:50] [Server thread/ERROR] [DynamX]: Cannot load terrain save at VCP[-73, 4, 26], invalidating it...
 java.lang.IllegalStateException: Cannot load an errored terrain element !
        at fr.dynamx.common.physics.terrain.element.TerrainElementsFactory.lambda$static$0(TerrainElementsFactory.java:12) ~[TerrainElementsFactory.class:?]
        at fr.dynamx.common.physics.terrain.element.TerrainElementsFactory.call(TerrainElementsFactory.java:27) ~[TerrainElementsFactory.class:?]
        at fr.dynamx.common.physics.terrain.element.TerrainElementsFactory.getById(TerrainElementsFactory.java:33) ~[TerrainElementsFactory.class:?]
        at fr.dynamx.common.physics.terrain.cache.VirtualTerrainFile.loadChunk(VirtualTerrainFile.java:92) ~[VirtualTerrainFile.class:?]
        at fr.dynamx.common.physics.terrain.cache.FileTerrainCache.load(FileTerrainCache.java:165) ~[FileTerrainCache.class:?]
        at fr.dynamx.common.physics.terrain.chunk.ChunkCollisions.loadCollisionsSync(ChunkCollisions.java:300) ~[ChunkCollisions.class:?]
        at fr.dynamx.common.physics.terrain.PhysicsWorldTerrain.loadChunkCollisionsNow(PhysicsWorldTerrain.java:322) ~[PhysicsWorldTerrain.class:?]
        at fr.dynamx.common.physics.terrain.PhysicsWorldTerrain.subscribeToChunk(PhysicsWorldTerrain.java:142) ~[PhysicsWorldTerrain.class:?]
        at fr.dynamx.common.physics.terrain.PhysicsEntityTerrainLoader.lambda$update$0(PhysicsEntityTerrainLoader.java:90) ~[PhysicsEntityTerrainLoader.class:?]
        at java.util.HashMap.forEach(HashMap.java:1290) ~[?:1.8.0_312]
        at fr.dynamx.common.physics.terrain.PhysicsEntityTerrainLoader.update(PhysicsEntityTerrainLoader.java:89) ~[PhysicsEntityTerrainLoader.class:?]
        at fr.dynamx.common.physics.world.BasePhysicsWorld.lambda$stepSimulationImpl$0(BasePhysicsWorld.java:135) ~[BasePhysicsWorld.class:?]
        at java.util.ArrayList.forEach(ArrayList.java:1259) [?:1.8.0_312]
        at fr.dynamx.common.physics.world.BasePhysicsWorld.stepSimulationImpl(BasePhysicsWorld.java:128) [BasePhysicsWorld.class:?]
        at fr.dynamx.common.physics.world.BuiltinPhysicsWorld.stepSimulation(BuiltinPhysicsWorld.java:45) [BuiltinPhysicsWorld.class:?]
        at fr.dynamx.common.physics.PhysicsTickHandler.tickWorldPhysics(PhysicsTickHandler.java:127) [PhysicsTickHandler.class:?]
        at fr.dynamx.common.physics.PhysicsTickHandler.tickServer(PhysicsTickHandler.java:89) [PhysicsTickHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_171_PhysicsTickHandler_tickServer_ServerTickEvent.invoke(.dynamic) [?:1.12.2-a0c0ffb0]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:1.12.2-a0c0ffb0]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:1.12.2-a0c0ffb0]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:283) [FMLCommonHandler.class:1.12.2-a0c0ffb0]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[08:50:50] [Server thread/ERROR] [DynamX]: Failed to add fr.dynamx.common.physics.terrain.element.DynamXBlockTerrainElement@1435e12e in ChunkCollisions[x=-73;y=4;z=26]
 java.lang.IllegalStateException: DynamX block TE failed to load at (-1168.0, 64.0, 416.0)
        at fr.dynamx.common.physics.terrain.element.DynamXBlockTerrainElement.build(DynamXBlockTerrainElement.java:68) ~[DynamXBlockTerrainElement.class:?]
        at fr.dynamx.common.physics.terrain.chunk.ChunkCollisions.lambda$localLoadCollisions$5(ChunkCollisions.java:400) ~[ChunkCollisions.class:?]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_312]
        at fr.dynamx.common.physics.terrain.chunk.ChunkCollisions.localLoadCollisions(ChunkCollisions.java:398) ~[ChunkCollisions.class:?]
        at fr.dynamx.common.physics.terrain.chunk.ChunkCollisions.loadCollisionsSync(ChunkCollisions.java:301) ~[ChunkCollisions.class:?]
        at fr.dynamx.common.physics.terrain.PhysicsWorldTerrain.loadChunkCollisionsNow(PhysicsWorldTerrain.java:322) ~[PhysicsWorldTerrain.class:?]
        at fr.dynamx.common.physics.terrain.PhysicsWorldTerrain.subscribeToChunk(PhysicsWorldTerrain.java:142) ~[PhysicsWorldTerrain.class:?]
        at fr.dynamx.common.physics.terrain.PhysicsEntityTerrainLoader.lambda$update$0(PhysicsEntityTerrainLoader.java:90) ~[PhysicsEntityTerrainLoader.class:?]
        at java.util.HashMap.forEach(HashMap.java:1290) ~[?:1.8.0_312]
        at fr.dynamx.common.physics.terrain.PhysicsEntityTerrainLoader.update(PhysicsEntityTerrainLoader.java:89) ~[PhysicsEntityTerrainLoader.class:?]
        at fr.dynamx.common.physics.world.BasePhysicsWorld.lambda$stepSimulationImpl$0(BasePhysicsWorld.java:135) ~[BasePhysicsWorld.class:?]
        at java.util.ArrayList.forEach(ArrayList.java:1259) [?:1.8.0_312]
        at fr.dynamx.common.physics.world.BasePhysicsWorld.stepSimulationImpl(BasePhysicsWorld.java:128) [BasePhysicsWorld.class:?]
        at fr.dynamx.common.physics.world.BuiltinPhysicsWorld.stepSimulation(BuiltinPhysicsWorld.java:45) [BuiltinPhysicsWorld.class:?]
        at fr.dynamx.common.physics.PhysicsTickHandler.tickWorldPhysics(PhysicsTickHandler.java:127) [PhysicsTickHandler.class:?]
        at fr.dynamx.common.physics.PhysicsTickHandler.tickServer(PhysicsTickHandler.java:89) [PhysicsTickHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_171_PhysicsTickHandler_tickServer_ServerTickEvent.invoke(.dynamic) [?:1.12.2-a0c0ffb0]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:1.12.2-a0c0ffb0]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:1.12.2-a0c0ffb0]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:283) [FMLCommonHandler.class:1.12.2-a0c0ffb0]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[08:50:50] [Server thread/ERROR] [DynamX]: Cannot load terrain save at VCP[-72, 4, 26], invalidating it...
```

**To Reproduce**
1. Use the DynamX and a mod with a MCreator mod (which contains tiles)

**Server:**
 - Linux (Debian)
 - DynamX 4.0 Beta 14

**Comment by AymericBdy** [comment]
Can't be reproduced.
