### ISSUE TITLE
Minecraft cannot launch with latest dynamX Version

### ISSUE THREAD

**Issue by BlackNiteHD** [DynamXInc/DynamX#39]
The problem is the mixin concerning player collision, because when it is removed from the mixins.json, everything works fine but there isn't any collision obviously.

```
[23:43:40] [Client thread/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/entity/Entity.func_70091_d(Lnet/minecraft/entity/MoverType;DDD)V @796: dload_3
  Reason:
    Type double_2nd (current frame, locals[3]) is not assignable to double
  Current Frame:
    bci: @796
    flags: { }
    locals: { 'net/minecraft/entity/Entity', 'net/minecraft/entity/MoverType', double, double_2nd, double, double_2nd, double, double_2nd, double, double_2nd, top, top, top, double, double_2nd, double, double_2nd, double, double_2nd, double, double_2nd, double, double_2nd, top, top, 'java/util/List' }
    stack: { 'net/minecraft/util/math/AxisAlignedBB', 'net/minecraft/entity/Entity' }
  Bytecode:
    0x0000000: 2ab4 029a 9900 1a2a 2ab6 0197 2818 0418
    0x0000010: 06b6 028e b601 bb2a b602 9da7 0a2b 2bb2
    0x0000020: 02a0 a600 f92a b401 16b6 02a4 3708 1608
    0x0000030: 2ab4 02a6 9499 0011 2ab4 0114 0eb8 02ac
    0x0000040: 2a16 08b5 02a6 280e 9799 0042 b202 b0b6
    0x0000050: 02b3 360a 282a b401 1415 0a31 6314 02b4
    0x0000060: 1402 b6b8 02bb 390b 180b 2ab4 0114 150a
    0x0000070: 3167 492a b401 1415 0a18 0b52 28b8 02c1
    0x0000080: 1402 c298 9d00 04b1 a700 9318 040e 9799
    0x0000090: 0045 b202 c6b6 02b3 360a 1804 2ab4 0114
    0x00000a0: 150a 3163 1402 b414 02b6 b802 bb39 0b18
    0x00000b0: 0b2a b401 1415 0a31 6739 042a b401 1415
    0x00000c0: 0a18 0b52 1804 b802 c114 02c2 989d 0004
    0x00000d0: b1a7 004a 1806 0e97 9a00 04b1 b202 c8b6
    0x00000e0: 02b3 360a 1806 2ab4 0114 150a 3163 1402
    0x00000f0: b414 02b6 b802 bb39 0b18 0b2a b401 1415
    0x0000100: 0a31 6739 062a b401 1415 0a18 0b52 1806
    0x0000110: b802 c114 02c2 989d 0004 b12a b401 16b4
    0x0000120: 0207 1302 cab6 020f 2ab4 0191 3908 2ab4
    0x0000130: 018d 390d 2ab4 0193 390f 2ab4 02cc 9900
    0x0000140: 2d2a 03b5 02cc 2814 02cd 6b49 1804 1402
    0x0000150: cf6b 3904 1806 1402 cd6b 3906 2a0e b501
    0x0000160: a32a 0eb5 01a5 2a0e b501 a728 3911 1804
    0x0000170: 3913 1806 3915 2bb2 01cd a500 0a2b b202
    0x0000180: d3a6 0165 2ab4 02d5 9901 5e2a b602 d899
    0x0000190: 0157 2ac1 02da 9901 5014 02db 3917 280e
    0x00001a0: 9799 0052 2ab4 0116 2a2a b601 9728 2ab4
    0x00001b0: 02de 768d 0eb6 028e b601 9bb9 01a1 0100
    0x00001c0: 9900 3328 1402 db98 9c00 1028 1402 df97
    0x00001d0: 9b00 080e 49a7 0018 280e 979e 000c 2814
    0x00001e0: 02db 6749 a700 0928 1402 db63 4928 3911
    0x00001f0: a7ff ae18 060e 9799 005c 2ab4 0116 2a2a
    0x0000200: b601 970e 2ab4 02de 768d 1806 b602 8eb6
    0x0000210: 019b b901 a101 0099 003c 1806 1402 db98
    0x0000220: 9c00 1218 0614 02df 979b 0009 0e39 06a7
    0x0000230: 001d 1806 0e97 9e00 0e18 0614 02db 6739
    0x0000240: 06a7 000b 1806 1402 db63 3906 1806 3915
    0x0000250: a7ff a328 0e97 9900 9018 060e 9799 0089
    0x0000260: 2ab4 0116 2a2a b601 9728 2ab4 02de 768d
    0x0000270: 1806 b602 8eb6 019b b901 a101 0099 0069
    0x0000280: 2814 02db 989c 0010 2814 02df 979b 0008
    0x0000290: 0e49 a700 1828 0e97 9e00 0c28 1402 db67
    0x00002a0: 49a7 0009 2814 02db 6349 2839 1118 0614
    0x00002b0: 02db 989c 0012 1806 1402 df97 9b00 090e
    0x00002c0: 3906 a700 1d18 060e 979e 000e 1806 1402
    0x00002d0: db67 3906 a700 0b18 0614 02db 6339 0618
    0x00002e0: 0639 15a7 ff70 2ab4 0116 2a2a b601 9728
    0x00002f0: 1804 1806 b602 e3b6 019b 3a19 2ab6 0197
    0x0000300: 2a2b 2818 0418 06bb 02e5 5913 02e6 03b7
    0x0000310: 02e9 b702 ed2a 28b7 02f0 492a 29b7 02f3
    0x0000320: 4a2a 1804 b702 f639 043a 1a18 040e 9799
    0x0000330: 0042 0336 1b19 19b9 02f7 0100 361c 151b
    0x0000340: 151c a200 2019 1915 1bb9 02fb 0200 c001
    0x0000350: b42a b601 9718 04b6 02ff 3904 841b 01a7
    0x0000360: ffdf 2a2a b601 970e 1804 0eb6 028e b601
    0x0000370: bb28 0e97 9900 4503 361b 1919 b902 f701
    0x0000380: 0036 1c15 1b15 1ca2 001e 1919 151b b902
    0x0000390: fb02 00c0 01b4 2ab6 0197 28b6 0302 4984
    0x00003a0: 1b01 a7ff e128 0e97 9900 112a 2ab6 0197
    0x00003b0: 280e 0eb6 028e b601 bb18 060e 9799 0049
    0x00003c0: 0336 1b19 19b9 02f7 0100 361c 151b 151c
    0x00003d0: a200 2019 1915 1bb9 02fb 0200 c001 b42a
    0x00003e0: b601 9718 06b6 0305 3906 841b 01a7 ffdf
    0x00003f0: 1806 0e97 9900 122a 2ab6 0197 0e0e 1806
    0x0000400: b602 8eb6 01bb 2a2a 28b7 0308 492a 29b7
    0x0000410: 030b 4a2a 1804 b703 0e39 04b4 02d5 9a00
    0x0000420: 1218 1318 0497 9900 0e18 130e 989c 0007
    0x0000430: 04a7 0004 0336 1b2a 151b b703 1236 1b2a
    0x0000440: b402 de0b 959e 0283 151b 9902 7e18 1128
    0x0000450: 979a 000b 1815 1806 9799 026f 2839 1d18
    0x0000460: 0439 1f18 0639 212a b601 973a 232a 191a
    0x0000470: b601 bb2a b402 de8d 3904 2ab4 0116 2a2a
    0x0000480: b601 9718 1118 0418 15b6 02e3 b601 9b3a
    0x0000490: 242a b601 973a 2519 2518 110e 1815 b602
    0x00004a0: e33a 2618 0439 2703 3629 1924 b902 f701
    0x00004b0: 0036 2a15 2915 2aa2 001e 1924 1529 b902
    0x00004c0: fb02 00c0 01b4 1926 1827 b602 ff39 2784
    0x00004d0: 2901 a7ff e119 250e 1827 0eb6 028e 3a25
    0x00004e0: 1811 392b 0336 2d19 24b9 02f7 0100 362e
    0x00004f0: 152d 152e a200 1e19 2415 2db9 02fb 0200
    0x0000500: c001 b419 2518 2bb6 0302 392b 842d 01a7
    0x0000510: ffe1 1925 182b 0e0e b602 8e3a 2518 1539
    0x0000520: 2f03 3631 1924 b902 f701 0036 3215 3115
    0x0000530: 32a2 001e 1924 1531 b902 fb02 00c0 01b4
    0x0000540: 1925 182f b603 0539 2f84 3101 a7ff e119
    0x0000550: 250e 0e18 2fb6 028e 3a25 2ab6 0197 3a32
    0x0000560: 1804 3933 0336 3519 24b9 02f7 0100 3636
    0x0000570: 1535 1536 a200 1e19 2415 35b9 02fb 0200
    0x0000580: c001 b419 3218 33b6 02ff 3933 8435 01a7
    0x0000590: ffe1 1932 0e18 330e b602 8e3a 3218 1139
    0x00005a0: 3703 3639 1924 b902 f701 0036 3a15 3915
    0x00005b0: 3aa2 001e 1924 1539 b902 fb02 00c0 01b4
    0x00005c0: 1932 1837 b603 0239 3784 3901 a7ff e119
    0x00005d0: 3218 370e 0eb6 028e 3a32 1815 393b 0336
    0x00005e0: 3d19 24b9 02f7 0100 363e 153d 153e a200
    0x00005f0: 1e19 2415 3db9 02fb 0200 c001 b419 3218
    0x0000600: 3bb6 0305 393b 843d 01a7 ffe1 1932 0e0e
    0x0000610: 183b b602 8e3a 3218 2b18 2b6b 182f 182f
    0x0000620: 6b63 393f 1837 1837 6b18 3b18 3b6b 6339
    0x0000630: 4118 3f18 4197 9e00 1818 2b49 182f 3906
    0x0000640: 1827 7739 042a 1925 b601 bba7 0015 1837
    0x0000650: 4918 3b39 0618 3377 3904 2a19 32b6 01bb
    0x0000660: 0336 4319 24b9 02f7 0100 3644 1543 1544
    0x0000670: a200 2019 2415 43b9 02fb 0200 c001 b42a
    0x0000680: b601 9718 04b6 02ff 3904 8443 01a7 ffdf
    0x0000690: 2a2a b601 970e 1804 0eb6 028e b601 bb18
    0x00006a0: 1d18 1d6b 1821 1821 6b63 2828 6b18 0618
    0x00006b0: 066b 6397 9b00 1418 1d49 181f 3904 1821
    0x00006c0: 3906 2a19 23b6 01bb 2ab4 0116 b402 07b6
    0x00006d0: 0251 2ab4 0116 b402 0713 0314 b602 0f2a
    0x00006e0: b602 9d2a 1811 2897 9a00 0b18 1518 0697
    0x00006f0: 9900 0704 a700 0403 b503 162a 1813 1804
    0x0000700: 9799 0007 04a7 0004 03b5 0318 2a2a b403
    0x0000710: 1899 000e 1813 0e98 9c00 0704 a700 0403
    0x0000720: b502 d52a 2ab4 0316 9a00 0a2a b403 1899
    0x0000730: 0007 04a7 0004 03b5 031a 2ab4 0191 b803
    0x0000740: 1e36 1c2a b401 8d14 031f 67b8 031e 3645
    0x0000750: 2ab4 0193 b803 1e36 46bb 001c 5915 1c15
    0x0000760: 4515 46b7 0323 3a47 2ab4 0116 1947 b603
    0x0000770: 273a 4819 48b9 032d 0100 b203 33a6 003e
    0x0000780: 1947 b603 373a 492a b401 1619 49b6 0327
    0x0000790: 3a23 1923 b903 3b01 003a 2419 24c1 033d
    0x00007a0: 9a00 1319 24c1 033f 9a00 0b19 24c1 0341
    0x00007b0: 9900 0b19 233a 4819 493a 472a 1804 2ab4
    0x00007c0: 02d5 1948 1947 b603 4518 1128 9799 0008
    0x00007d0: 2a0e b501 a318 1518 0697 9900 082a 0eb5
    0x00007e0: 01a7 1948 b903 3b01 003a 4918 1318 0497
    0x00007f0: 9900 0d19 492a b401 162a b603 4b2a b603
    0x0000800: 4e99 018a 2ab4 02d5 9900 112a b602 d899
    0x0000810: 000a 2ac1 02da 9a01 752a b602 129a 016e
    0x0000820: 2ab4 0191 1808 6739 4a2a b401 8d18 0d67
    0x0000830: 394c 2ab4 0193 180f 6739 2719 49b2 0354
    0x0000840: a500 060e 394c 1949 c600 162a b402 d599
    0x0000850: 000f 1949 2ab4 0116 1947 2ab6 0358 2a2a
    0x0000860: b402 1d8d 184a 184a 6b18 2718 276b 63b8
    0x0000870: 035c 8d14 035d 6b63 90b5 021d 2a2a b403
    0x0000880: 608d 184a 184a 6b18 4c18 4c6b 6318 2718
    0x0000890: 276b 63b8 035c 8d14 035d 6b63 90b5 0360
    0x00008a0: 2ab4 0360 2ab4 00e8 8695 9e00 b519 48b9
    0x00008b0: 032d 0100 b203 33a5 00a8 2a2a b403 608b
    0x00008c0: 0460 b500 e82a b603 6399 008b 2ab6 0366
    0x00008d0: 9900 112a b603 69c6 000a 2ab6 0369 a700
    0x00008e0: 042a 3a29 1929 2aa6 0009 1303 6aa7 0006
    0x00008f0: 1303 6b38 2a19 29b4 01a3 1929 b401 a36b
    0x0000900: 1403 1f6b 1929 b401 a519 29b4 01a5 6b63
    0x0000910: 1929 b401 a719 29b4 01a7 6b14 031f 6b63
    0x0000920: b803 5c17 2a6a 384e 174e 0c95 9e00 060c
    0x0000930: 384e 2a2a b603 6f17 4e0c 2ab4 00ef b603
    0x0000940: 732a b400 efb6 0373 6613 036b 6a62 b603
    0x0000950: 77a7 003a 2a19 4719 49b6 037b a700 2f2a
    0x0000960: b403 602a b400 ea95 9e00 232a b603 7e99
    0x0000970: 001c 1948 b903 2d01 00b2 0333 a600 0f2a
    0x0000980: 2a2a b403 60b6 0382 b500 ea2a b603 85a7
    0x0000990: 0029 3a23 1923 1303 87b8 038d 3a24 1924
    0x00009a0: 1303 8fb6 0393 3a25 2a19 25b6 0397 bb03
    0x00009b0: 9959 1924 b703 9cbf 2ab6 039f 3623 2ab4
    0x00009c0: 0116 2ab6 0197 1403 a0b6 03a5 b603 a899
    0x00009d0: 0027 2a04 b603 ab15 239a 002d 2a59 b400
    0x00009e0: f504 60b5 00f5 2ab4 00f5 9a00 1c2a 1008
    0x00009f0: b602 7fa7 0013 2ab4 00f5 9d00 0c2a 2ab6
    0x0000a00: 00f3 74b5 00f5 1523 9900 342a b603 ae99
    0x0000a10: 002d 2ab2 03b4 1303 b513 03b6 2ab4 00ef
    0x0000a20: b603 732a b400 efb6 0373 6613 036b 6a62
    0x0000a30: b603 772a 2ab6 00f3 74b5 00f5 2ab4 0116
    0x0000a40: b402 07b6 0251 b1                      
  Exception Handler Table:
    bci [2443, 2447] => handler: 2450
  Stackmap Table:
    same_frame(@30)
    append_frame(@70,Long)
    append_frame(@136,Integer,Double)
    chop_frame(@139,2)
    append_frame(@209,Integer,Double)
    chop_frame(@212,2)
    same_frame(@220)
    chop_frame(@283,1)
    full_frame(@363,{Object[#2],Object[#457],Double,Double,Double,Double,Top,Top,Top,Double,Double},{})
    append_frame(@388,Double,Double,Double)
    append_frame(@414,Double)
    same_frame(@472)
    same_frame(@487)
    same_frame(@493)
    same_frame(@499)
    same_frame(@562)
    same_frame(@580)
    same_frame(@588)
    same_frame(@595)
    same_frame_extended(@661)
    same_frame(@676)
    same_frame(@682)
    same_frame(@709)
    same_frame(@727)
    same_frame(@735)
    chop_frame(@742,1)
    full_frame(@830,{Object[#2],Object[#457],Top,Top,Double,Double,Double,Top,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#413],Object[#436],Integer,Integer},{})
    same_frame(@866)
    chop_frame(@881,2)
    append_frame(@899,Integer,Integer)
    same_frame(@933)
    chop_frame(@953,2)
    append_frame(@972,Integer,Integer)
    same_frame(@1008)
    chop_frame(@1030,2)
    same_frame(@1072)
    same_frame(@1076)
    same_locals_1_stack_item_frame(@1077,Integer)
    append_frame(@1116,Integer)
    full_frame(@1203,{Object[#2],Object[#457],Top,Top,Double,Double,Double,Top,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#413],Object[#436],Integer,Top,Double,Double,Double,Object[#436],Object[#413],Object[#436],Object[#436],Double,Integer,Integer},{})
    same_frame(@1237)
    append_frame(@1264,Double,Integer,Integer)
    same_frame(@1298)
    append_frame(@1325,Double,Integer,Integer)
    same_frame(@1359)
    full_frame(@1392,{Object[#2],Object[#457],Top,Top,Double,Double,Double,Top,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#413],Object[#436],Integer,Top,Double,Double,Double,Object[#436],Object[#413],Object[#436],Object[#436],Double,Integer,Integer,Double,Integer,Integer,Double,Integer,Object[#436],Double,Integer,Integer},{})
    same_frame(@1426)
    append_frame(@1453,Double,Integer,Integer)
    same_frame(@1487)
    append_frame(@1514,Double,Integer,Integer)
    same_frame(@1548)
    append_frame(@1614,Double,Double)
    full_frame(@1632,{Object[#2],Object[#457],Double,Double,Double,Double,Top,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#413],Object[#436],Integer,Top,Double,Double,Double,Object[#436],Object[#413],Object[#436],Object[#436],Double,Integer,Integer,Double,Integer,Integer,Double,Integer,Object[#436],Double,Integer,Integer,Double,Integer,Integer,Double,Integer,Integer,Double,Double},{})
    append_frame(@1644,Integer,Integer)
    same_frame(@1680)
    full_frame(@1736,{Object[#2],Object[#457],Top,Top,Double,Double,Double,Top,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#413],Object[#436],Integer},{})
    same_locals_1_stack_item_frame(@1779,Object[#2])
    same_locals_1_stack_item_frame(@1783,Object[#2])
    full_frame(@1784,{Object[#2],Object[#457],Top,Top,Double,Double,Double,Top,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#413],Object[#436],Integer},{Object[#2],Integer})
    same_locals_1_stack_item_frame(@1800,Object[#2])
    full_frame(@1801,{Object[#2],Object[#457],Top,Top,Double,Double,Double,Top,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#413],Object[#436],Integer},{Object[#2],Integer})
    same_locals_1_stack_item_frame(@1823,Object[#2])
    full_frame(@1824,{Object[#2],Object[#457],Top,Top,Double,Double,Double,Top,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#413],Object[#436],Integer},{Object[#2],Integer})
    same_locals_1_stack_item_frame(@1842,Object[#2])
    same_locals_1_stack_item_frame(@1846,Object[#2])
    full_frame(@1847,{Object[#2],Object[#457],Top,Top,Double,Double,Double,Top,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#413],Object[#436],Integer},{Object[#2],Integer})
    full_frame(@1971,{Object[#2],Object[#457],Top,Top,Double,Double,Double,Top,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#413],Object[#436],Integer,Integer,Top,Top,Top,Top,Top,Top,Object[#809],Object[#839],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Integer,Object[#28],Object[#809],Object[#28]},{})
    full_frame(@1979,{Object[#2],Object[#457],Top,Top,Double,Double,Double,Top,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#413],Object[#436],Integer,Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Integer,Object[#28],Object[#809]},{})
    same_frame(@2005)
    same_frame(@2018)
    append_frame(@2045,Object[#839])
    same_frame(@2073)
    full_frame(@2118,{Object[#2],Object[#457],Top,Top,Double,Double,Double,Top,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#413],Object[#436],Integer,Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Double,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Integer,Object[#28],Object[#809],Object[#839],Double,Double},{})
    same_frame(@2142)
    same_frame_extended(@2273)
    same_locals_1_stack_item_frame(@2274,Object[#2])
    full_frame(@2288,{Object[#2],Object[#457],Top,Top,Double,Double,Double,Top,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#413],Object[#436],Integer,Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Double,Object[#2],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Integer,Object[#28],Object[#809],Object[#839],Double,Double},{})
    same_locals_1_stack_item_frame(@2291,Float)
    full_frame(@2354,{Object[#2],Object[#457],Top,Top,Double,Double,Double,Top,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#413],Object[#436],Integer,Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Double,Object[#2],Float,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Integer,Object[#28],Object[#809],Object[#839],Double,Double,Float},{})
    full_frame(@2388,{Object[#2],Object[#457],Top,Top,Double,Double,Double,Top,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#413],Object[#436],Integer,Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Double,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Integer,Object[#28],Object[#809],Object[#839],Double,Double},{})
    same_frame(@2399)
    full_frame(@2443,{Object[#2],Object[#457],Top,Top,Double,Double,Double,Top,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#413],Object[#436],Integer,Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Integer,Object[#28],Object[#809],Object[#839]},{})
    same_locals_1_stack_item_frame(@2450,Object[#664])
    same_frame(@2488)
    full_frame(@2550,{Object[#2],Object[#457],Top,Top,Double,Double,Double,Top,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#413],Object[#436],Integer,Integer,Top,Top,Top,Top,Top,Top,Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Integer,Object[#28],Object[#809],Object[#839]},{})
    same_frame(@2566)
    same_frame(@2620)
    full_frame(@2630,{Object[#2],Object[#457],Top,Top,Double,Double},{})

	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_332]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_332]
	at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_332]
	at java.lang.Class.getConstructor(Class.java:1825) ~[?:1.8.0_332]
	at net.minecraft.entity.EntityList.func_191303_a(EntityList.java:410) ~[vi.class:?]
	at net.minecraft.entity.EntityList.func_151514_a(EntityList.java:277) ~[vi.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:505) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
[23:43:40] [Client thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[23:43:40] [Client thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[23:43:40] [Client thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[23:43:40] [Client thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[23:43:40] [Client thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:973)
[23:43:40] [Client thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[23:43:40] [Client thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by AymericBdy** [comment]
Was a configuration error on the player side
